{
 "title": "go-zero-mall",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "api_app", "label": "API服务名称", "query": { "query": "label_values(app)" } },
   { "name": "rpc_app", "label": "RPC服务名称", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "RPC接口状态码",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_requests_code_total{app=\"$rpc_app\"}[5m])) by (code)"
    }
   ]
  },
  {
   "title": "API接口状态码",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_code_total{app=\"$api_app\"}[5m])) by (code)"
    }
   ]
  },
  {
   "title": "RPC接口QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_requests_duration_ms_count{app=\"$rpc_app\"}[5m])) by (method)"
    }
   ]
  },
  {
   "title": "API接口QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_duration_ms_count{app=\"$api_app\"}[5m])) by (path)"
    }
   ]
  }
 ]
}