// Code generated by goctl. DO NOT EDIT!
// Source: pay.proto

package pay

import (
	"context"

	"mall/service/pay/rpc/payclient"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CallbackRequest  = payclient.CallbackRequest
	CallbackResponse = payclient.CallbackResponse
	CreateRequest    = payclient.CreateRequest
	CreateResponse   = payclient.CreateResponse
	DetailRequest    = payclient.DetailRequest
	DetailResponse   = payclient.DetailResponse

	Pay interface {
		Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
		Detail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error)
		Callback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error)
	}

	defaultPay struct {
		cli zrpc.Client
	}
)

func NewPay(cli zrpc.Client) Pay {
	return &defaultPay{
		cli: cli,
	}
}

func (m *defaultPay) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	client := payclient.NewPayClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

func (m *defaultPay) Detail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error) {
	client := payclient.NewPayClient(m.cli.Conn())
	return client.Detail(ctx, in, opts...)
}

func (m *defaultPay) Callback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error) {
	client := payclient.NewPayClient(m.cli.Conn())
	return client.Callback(ctx, in, opts...)
}
