name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Lint Go Code
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint 
        golint -set_exit_status
        
    - name: Run Unit tests
      run: |
        go test -short -coverprofile cover.out -covermode=atomic $(shell go list ./... | grep -v /vendor/ | grep -v /docker/)
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.out	
    - name: Build
      run: |
        go version
        go mod tidy
        mkdir build
        go build -o build/user-rpc ./service/user/rpc
        go build -o build/user-api ./service/user/api
        go build -o build/product-rpc ./service/product/rpc
        go build -o build/product-api ./service/product/api
        go build -o build/order-rpc ./service/order/rpc
        go build -o build/order-api ./service/order/api
        go build -o build/pay-rpc ./service/pay/rpc
        go build -o build/pay-api ./service/pay/api
        ls build
        
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2.3.1
      with: 
          name: assets-for-download
          path: build
