name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go version
        go mod tidy
        mkdir build
        go build -i -o build/user-rpc ./service/user/rpc
        go build -i -o build/user-api ./service/user/api
        go build -i -o build/product-rpc ./service/product/rpc
        go build -i -o build/product-api ./service/product/api
        go build -i -o build/order-rpc ./service/order/rpc
        go build -i -o build/order-api ./service/order/api
        go build -i -o build/pay-rpc ./service/pay/rpc
        go build -i -o build/pay-api ./service/pay/api
        ls build
